# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('codigoDoctor', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigoEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('apellidoPrimero', models.CharField(max_length=15, verbose_name='Primer Apellido')),
                ('apellidoSegundo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Apellido')),
                ('nombrePrimero', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('nombreSegundo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Nombre')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('fechaNacimiento', models.DateField(help_text='DD/MM/YYYY', verbose_name='Fecha de Nacimiento')),
                ('cargo', models.CharField(choices=[('D', 'Doctor'), ('E', 'Enfermera'), ('A', 'Personal de Archivo'), ('P', 'Personal Administrativo'), ('O', 'Otros')], default='P', max_length=1)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripcion')),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recibio la informacion')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='codigoEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Especialidad', verbose_name='Especialidad'),
        ),
    ]
