# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleadosapp', '0001_initial'),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cola_Consulta',
            fields=[
                ('idCola', models.AutoField(primary_key=True, serialize=False)),
                ('idDoctor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleadosapp.Doctor', verbose_name='Doctor')),
                ('idPaciente', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datospersonalesapp.Paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cola_Enfermeria',
            fields=[
                ('idCola', models.AutoField(primary_key=True, serialize=False)),
                ('idPaciente', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datospersonalesapp.Paciente', verbose_name='Paciente')),
            ],
        ),
    ]
