# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeriaapp', '0002_cola_enfermeria_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cola_consulta',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
