# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeriaapp', '0003_cola_consulta_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cola_consulta',
            name='idPaciente',
        ),
        migrations.AddField(
            model_name='cola_consulta',
            name='nit',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='NIT'),
        ),
    ]
