# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeriaapp', '0004_auto_20161230_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola_consulta',
            name='nit',
            field=models.CharField(max_length=17, unique=True, verbose_name='NIT'),
        ),
    ]
