# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleadosapp', '0001_initial'),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLab',
            fields=[
                ('codigoArea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreArea', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_paciente', models.CharField(max_length=17)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tipo_consulta', models.CharField(choices=[('PRV', 'Primera vez'), ('SUB', 'Subsecuente')], default='PRV', max_length=50)),
                ('consulta_por', models.TextField()),
                ('presenta_enfermedad', models.TextField(blank=True)),
                ('antecedentes_personales', models.TextField(blank=True)),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('exploracion_clinica', models.TextField()),
                ('diagnostico_principal', models.CharField(blank=True, max_length=500)),
                ('otros_diagnosticos', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor')),
                ('cod_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='db29179_cie10',
            fields=[
                ('id10', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dec10', models.CharField(max_length=400)),
                ('grp10', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLab',
            fields=[
                ('codigoExamen', models.AutoField(primary_key=True, serialize=False)),
                ('nombreExamen', models.CharField(max_length=400)),
                ('codArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalapp.AreaLab')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalapp.AreaLab')),
                ('codExamen', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='codArea', chained_model_field='codArea', on_delete=django.db.models.deletion.CASCADE, to='generalapp.ExamenLab')),
                ('cod_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalapp.Consulta')),
                ('cod_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor')),
                ('cod_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('medicamento', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalapp.Consulta')),
                ('cod_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor')),
                ('cod_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('edad_paciente', models.PositiveSmallIntegerField()),
                ('sexo_paciente', models.CharField(max_length=1)),
                ('domicilio_paciente', models.CharField(max_length=500)),
                ('telefono_paciente', models.CharField(max_length=9)),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField()),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.PositiveSmallIntegerField()),
                ('talla', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consulta_por', models.TextField()),
                ('presenta_enfermedad', models.TextField(blank=True)),
                ('antecedentes_personales', models.TextField(blank=True)),
                ('examen_fisico', models.TextField()),
                ('examenes_laboratorio', models.TextField(blank=True)),
                ('impresion_diagnostica', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalapp.Consulta')),
                ('cod_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor')),
                ('cod_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('referido_a', models.CharField(max_length=500)),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('tipo_paciente', models.CharField(max_length=200)),
                ('procedencia_paciente', models.CharField(max_length=200)),
                ('motivo_referencia', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalapp.Consulta')),
                ('cod_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor')),
                ('cod_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente')),
            ],
        ),
    ]
