# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0002_auto_20161112_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('PRV', 'Primera vez'), ('SUB', 'Subsecuente')], max_length=50),
        ),
    ]
