# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0004_forma_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciaexterna',
            name='referido_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
