# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0005_referenciaexterna_referido_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='visto_bueno',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
