# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0006_consulta_visto_bueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciaexterna',
            name='referido_a',
            field=models.CharField(max_length=500),
        ),
    ]
