# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0008_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAsistencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
