# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('codigoSignosVitales', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveIntegerField()),
                ('presionArterial', models.CharField(max_length=7, verbose_name='Presion Arterial')),
                ('frecuenciaCardiaca', models.PositiveIntegerField(verbose_name='Frecuencia Cardiaca')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura')),
                ('peso', models.PositiveIntegerField()),
                ('talla', models.DecimalField(decimal_places=2, max_digits=3)),
                ('frecuenciaRespiratoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria')),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('horaIngreso', models.TimeField(auto_now_add=True)),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente', verbose_name='No expediente')),
            ],
        ),
    ]
