# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('codigoBusqueda', models.AutoField(primary_key=True, serialize=False)),
                ('consulta', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaBusqueda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigoDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=30, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('codigoFacultad', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombreFacultad', models.CharField(max_length=50, verbose_name='Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigoMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMunicipio', models.CharField(max_length=80, verbose_name='Municipio')),
                ('codDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codigoPaciente', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='No. de Expediente Clinico')),
                ('apellidoPrimero', models.CharField(max_length=15, verbose_name='Primer Apellido')),
                ('apellidoSegundo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Apellido')),
                ('nombrePrimero', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('nombreSegundo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Nombre')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('fechaNacimiento', models.DateField(help_text='DD/MM/YYYY', verbose_name='Fecha de Nacimiento')),
                ('estadoCivil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('ACOMPANADO', 'Acompanado(a)'), ('VIUDO', 'Viudo(a)')], default='SOLTERO', max_length=12, verbose_name='Estado Civil')),
                ('nit', models.CharField(max_length=17, unique=True, verbose_name='NIT')),
                ('dui', models.CharField(blank=True, max_length=10, null=True, verbose_name='DUI')),
                ('due', models.CharField(blank=True, max_length=7, null=True, verbose_name='DUE')),
                ('estadoUes', models.CharField(choices=[('EST', 'Estudiante'), ('DOC', 'Docente'), ('PAD', 'Pers.Administrativo'), ('OTR', 'Otro')], default='EST', max_length=3, verbose_name='Estado UES')),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombrePadre', models.CharField(blank=True, max_length=65, null=True, verbose_name='Nombre del Padre')),
                ('nombreMadre', models.CharField(blank=True, max_length=65, null=True, verbose_name='Nombre de la Madre')),
                ('nombrePareja', models.CharField(blank=True, max_length=65, null=True, verbose_name='Nombre del Conyuge')),
                ('emergencia', models.CharField(max_length=65, verbose_name='En caso de Emergencia avisar a')),
                ('telefonoEmergencia', models.CharField(max_length=9, verbose_name='Telefono')),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripcion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('estadoExpediente', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo')], default='A', max_length=1, verbose_name='Archivo')),
                ('codDepartamento', models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datospersonalesapp.Departamento', verbose_name='Departamento')),
                ('codMunicipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='codDepartamento', chained_model_field='codDepartamento', on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Municipio')),
                ('facultadE', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datospersonalesapp.Facultad', verbose_name='Facultad')),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion')),
            ],
        ),
    ]
