# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleadosapp', '0001_initial'),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('codigoCancelacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(help_text='DD/MM/YYYY', verbose_name='fecha inicio')),
                ('fechaFinal', models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='fecha final')),
                ('horaInicio', models.TimeField(verbose_name='Hora inicio')),
                ('horaFinal', models.TimeField(verbose_name='Hora final')),
                ('codigoDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor', verbose_name='Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('codigoCita', models.AutoField(primary_key=True, serialize=False)),
                ('fechaConsulta', models.DateField(help_text='DD/MM/YYYY', verbose_name='Fecha de la Consulta')),
                ('horaConsulta', models.TimeField(verbose_name='Hora de la consulta')),
                ('estadoConsulta', models.CharField(choices=[('N', 'Normal'), ('C', 'Cancelado'), ('R', 'Reprogramar')], default='N', max_length=1)),
                ('codigoDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente', verbose_name='No expediente')),
            ],
        ),
        migrations.CreateModel(
            name='diasSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('codigoHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField(verbose_name='Hora inicio')),
                ('horaFinal', models.TimeField(verbose_name='Hora final')),
                ('pacienteConsulta', models.PositiveIntegerField()),
                ('codigoDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor', verbose_name='Doctor')),
                ('dia', models.ManyToManyField(to='citasmedicasapp.diasSemana')),
            ],
        ),
    ]
