# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleadosapp', '0001_initial'),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoTerapeutico',
            fields=[
                ('codProcesoTerapeutico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name=b'Fecha')),
                ('objetivo', models.TextField(verbose_name=b'Objetivo Terapeutico')),
                ('tecnicas', models.CharField(choices=[(b'observacion', b'Observacion'), (b'entrevista', b'Entrevista'), (b'prueba', b'Prueba Pca'), (b'conv', b'Conv. Terapeutica'), (b'relajacion', b'Tecnica de relajacion'), (b'musico', b'Musicoterapia')], default=b'observacion', max_length=12, verbose_name=b'Tecnicas')),
                ('observaciones', models.TextField(verbose_name=b'Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologia',
            fields=[
                ('codPsicologia', models.AutoField(primary_key=True, serialize=False)),
                ('numero_hijos', models.PositiveSmallIntegerField(default=0, verbose_name=b'Numero de Hijos')),
                ('profesion', models.CharField(max_length=60, verbose_name=b'Profesion u Ocupacion')),
                ('fecha_primeraConsulta', models.DateField(help_text=b'DD/MM/AAAA', verbose_name=b'Fecha de Primera Consulta')),
                ('direccionResponsable', models.CharField(max_length=250, verbose_name=b'Direccion del Responsable')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name=b'Fecha')),
                ('religion', models.CharField(max_length=50, verbose_name=b'Religion')),
                ('familia', models.PositiveSmallIntegerField(verbose_name=b'Cuantos componen la familia')),
                ('motivo', models.TextField(verbose_name=b'Motivo de Consulta')),
                ('antecedentes', models.TextField(verbose_name=b'Antecedentes del Problema')),
                ('apariencia', models.CharField(max_length=120, verbose_name=b'Apariencia externa')),
                ('voz', models.CharField(max_length=30, verbose_name=b'Voz')),
                ('patrones', models.CharField(max_length=50, verbose_name=b'Patrones de Habla')),
                ('expresionesF', models.CharField(max_length=120, verbose_name=b'Expresiones Faciales')),
                ('ademanes', models.CharField(max_length=120, verbose_name=b'Ademanes')),
                ('actitudes_tx', models.TextField(verbose_name=b'Actitudes hacia el TX')),
                ('impresion_dx', models.TextField(verbose_name=b'Impresion DX')),
                ('plan_tx', models.TextField(verbose_name=b'Plan de TX')),
                ('pronostico', models.TextField(verbose_name=b'Pronostico')),
                ('fecha_proximaCita', models.DateField(help_text=b'DD/MM/AAAA', verbose_name=b'Fecha de Proxima Cita')),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Tomo informacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente', verbose_name=b'No expediente')),
                ('referido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor', verbose_name=b'Referido por')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAvance',
            fields=[
                ('codRegistroAvance', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateField(auto_now_add=True, verbose_name=b'fechaRegistro')),
                ('paciente', models.TextField(verbose_name=b'Paciente')),
                ('psicologo', models.TextField(verbose_name=b'Psicologo')),
                ('codProcesoTerapeutico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicologiaapp.ProcesoTerapeutico')),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Tomo informacion')),
            ],
        ),
        migrations.AddField(
            model_name='procesoterapeutico',
            name='codPsicologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicologiaapp.Psicologia'),
        ),
        migrations.AddField(
            model_name='procesoterapeutico',
            name='nombreRecibido',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Tomo informacion'),
        ),
    ]
