# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleadosapp', '0001_initial'),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_Enfermeria',
            fields=[
                ('codActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreActividad', models.CharField(max_length=20, verbose_name='Nombre Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Censo_Enfermeria',
            fields=[
                ('codCenso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fechaActividad', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Actividad')),
                ('actividad', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuevoingresoapp.Actividad_Enfermeria', verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado_Salud',
            fields=[
                ('codigoCertificado', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('enfermedadIC', models.BooleanField()),
                ('enfermedadICDetalle', models.CharField(blank=True, max_length=1000, null=True)),
                ('enfermedadEF', models.BooleanField()),
                ('enfermedadEFDetalle', models.CharField(blank=True, max_length=1000, null=True)),
                ('enfermedadSN', models.BooleanField()),
                ('enfermedadSNDetalle', models.CharField(blank=True, max_length=1000, null=True)),
                ('resultadoHIV', models.CharField(blank=True, max_length=100, null=True)),
                ('resultadoHECES', models.CharField(blank=True, max_length=100, null=True)),
                ('resultadoVDRL', models.CharField(blank=True, max_length=100, null=True)),
                ('resultadoHemograma', models.CharField(blank=True, max_length=100, null=True)),
                ('resultadoOrina', models.CharField(blank=True, max_length=100, null=True)),
                ('resultadoRX', models.CharField(blank=True, max_length=100, null=True)),
                ('presentaImpedimentos', models.BooleanField()),
                ('presentaImpedimentosDetalle', models.CharField(blank=True, max_length=1000, null=True)),
                ('aptoAprobado', models.BooleanField()),
                ('aptoAprobadoDetalle', models.CharField(blank=True, max_length=1000, null=True)),
                ('codigoDoctor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleadosapp.Doctor', verbose_name='Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_Provisional',
            fields=[
                ('Cod_Expediente_Provisional', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePrimero', models.CharField(max_length=15, verbose_name='Primer Nombre')),
                ('nombreSegundo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Nombre')),
                ('apellidoPrimero', models.CharField(max_length=15, verbose_name='Primer Apellido')),
                ('apellidoSegundo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Apellido')),
                ('fechaNacimiento', models.DateField(help_text='YYYY-MM-DD', verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripcion')),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=3)),
                ('presionArterial', models.CharField(max_length=7)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuenciaRespiratoria', models.PositiveIntegerField()),
                ('frecuenciaCardiaca', models.PositiveIntegerField()),
                ('Observaciones', models.CharField(blank=True, max_length=5000, null=True)),
                ('nit', models.CharField(max_length=17, unique=True, verbose_name='NIT')),
                ('facultad', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datospersonalesapp.Facultad', verbose_name='Facultad')),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion')),
            ],
        ),
        migrations.AddField(
            model_name='certificado_salud',
            name='codigoPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoingresoapp.Expediente_Provisional', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='certificado_salud',
            name='nombreRecibido',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion'),
        ),
    ]
