# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoingresoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad_enfermeria',
            name='fechaActividad',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 8, 21, 59, 59, 950829, tzinfo=utc), verbose_name='Fecha de Inscripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad_enfermeria',
            name='nombreActividad',
            field=models.CharField(max_length=50, verbose_name='Nombre Actividad'),
        ),
        migrations.AlterField(
            model_name='certificado_salud',
            name='aptoAprobado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='certificado_salud',
            name='enfermedadEF',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='certificado_salud',
            name='enfermedadIC',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='certificado_salud',
            name='enfermedadSN',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='certificado_salud',
            name='presentaImpedimentos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
