# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoingresoapp', '0002_auto_20161008_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente_provisional',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
    ]
