# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 22:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datospersonalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentosGrupo',
            fields=[
                ('codAlimentosGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('alimento', models.CharField(max_length=50, verbose_name='Alimento')),
            ],
        ),
        migrations.CreateModel(
            name='DatosNutricionales',
            fields=[
                ('codDatosNutricionales', models.AutoField(primary_key=True, serialize=False)),
                ('habitos', models.CharField(choices=[(1, 'Consume Licor'), (2, 'Fuma'), (3, 'Consumo de Sal extra'), (4, 'Consumo de Agua'), (5, 'Consumo de Cafe'), (6, 'Consumo de Chile')], max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Habitos')),
                ('alimentosPreferidos', models.TextField(verbose_name='Alimentos Preferidos')),
                ('alimentosIntolerados', models.TextField(verbose_name='Alimentos intolerados o rechazados')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('alimentos', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='grupoAlimentos', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, to='nutricionapp.AlimentosGrupo')),
            ],
        ),
        migrations.CreateModel(
            name='GruposAlimentos',
            fields=[
                ('codGrupoAlimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=8, verbose_name='Nombre de Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('codNutricion', models.AutoField(primary_key=True, serialize=False)),
                ('estructuraOsea', models.CharField(max_length=1, verbose_name='Estructura Osea')),
                ('extensionBrazada', models.PositiveSmallIntegerField()),
                ('circunferenciaCuerpo', models.PositiveSmallIntegerField()),
                ('pesoDeseable', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datospersonalesapp.Paciente', verbose_name='No expediente')),
            ],
        ),
        migrations.AddField(
            model_name='datosnutricionales',
            name='grupoAlimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutricionapp.GruposAlimentos', verbose_name='Grupo de Alimentos'),
        ),
        migrations.AddField(
            model_name='datosnutricionales',
            name='nombreRecibido',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion'),
        ),
        migrations.AddField(
            model_name='datosnutricionales',
            name='nutricion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricionapp.Nutricion'),
        ),
        migrations.AddField(
            model_name='alimentosgrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricionapp.GruposAlimentos'),
        ),
    ]
