# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='estructuraOsea',
            field=models.CharField(choices=[('p', 'Pequena'), ('m', 'Mediana'), ('g', 'Grande')], max_length=1, verbose_name='Estructura Osea'),
        ),
    ]
