# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionapp', '0002_auto_20161211_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosnutricionales',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='datosnutricionales',
            name='grupoAlimentos',
        ),
    ]
