# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutricionapp', '0003_auto_20161215_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('codAnamnesis', models.AutoField(primary_key=True, serialize=False)),
                ('tiempoComida', models.PositiveSmallIntegerField()),
                ('lugar', models.CharField(max_length=30, verbose_name='Lugar')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('alimentosConsumidos', models.CharField(max_length=100, verbose_name='Alimentos Consumidos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion')),
                ('nutricion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricionapp.Nutricion')),
            ],
        ),
        migrations.CreateModel(
            name='DatosClinicos',
            fields=[
                ('codDatosClinicos', models.AutoField(primary_key=True, serialize=False)),
                ('clinica', models.CharField(max_length=60, verbose_name='Clinica Referencia')),
                ('medico', models.CharField(max_length=60, verbose_name='Medico Referencia')),
                ('diagnosticoRef', models.TextField(verbose_name='Diagnostico de Referencia')),
                ('diagnosticoSec', models.TextField(verbose_name='Diagnostico Secundario')),
                ('medicamentos', models.TextField(verbose_name='Medicamentos usados')),
                ('deportes', models.TextField(verbose_name='Deportes Practicados')),
                ('tiempoPractica', models.PositiveSmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombreRecibido', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tomo informacion')),
                ('nutricion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricionapp.Nutricion')),
            ],
        ),
    ]
